---
abstract: 'Load/save bitmap from/to PDL (via FreeImage library)'
author:
  - 'KMX <kmx@cpan.org>'
build_requires:
  Alien::FreeImage: 0.011
  File::Temp: 0
  PDL: 2.006
  Test::More: 0
  Test::Number::Delta: 1.06
configure_requires:
  Alien::FreeImage: 0.011
  PDL: 2.006
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-IO-Image
no_index:
  directory:
    - t
    - inc
requires:
  Alien::FreeImage: 0.011
  PDL: 2.006
resources:
  repository: https://github.com/kmx/pdl-io-image
version: 0.004
